### PR TITLE
Add support to webpack 3

### PR DESCRIPTION
**Pull request by lucascarvalho**
Feel free to review, merge and publish a new version.

### CODE REVIEW

**Comment by fdanielsen** [comment]
In reference to #27, this solves the issue in a way that has worked for us for a while now. Literally line by line this is my implementation as [seen here](https://github.com/eliksir/manifest-revision-webpack-plugin/commit/882661339e53821240503ae5c2e6da1cabc80027), I guess great minds think alike ;)

I didn't have time to push my patch out as a PR during vacation etc., so feel free to get this merged and released. I have no idea why the CI fails though.

**Comment by lucascarvalho** [comment]
I tried to put everything together in one PR, including the `package.json` so other developers wouldn't have to search for the solution in all the forks. All the credits go to you @fdanielsen. :)

I've been using it since then and it works like a charm.
Thank you. (:

**Comment by nickjj** [comment]
It seems to failing specifically on Node 0.10, but passes on 0.11 and 0.12.

Details of the failure can be found at: https://travis-ci.org/nickjj/manifest-revision-webpack-plugin/jobs/254974805.

And the 2 passing runs can be seen here: https://travis-ci.org/nickjj/manifest-revision-webpack-plugin/builds/254974802

**Comment by lucascarvalho** [comment]
Hi @nickjj,
It seems to be working now. Let me know if you need something else.
Thanks. (:

**Comment by fdanielsen** [comment]
Seems like a simple fix to keep node 0.10 support. But for the future, Webpack hasn't officially supported node 0.10 in a while, so it might not be too important to keep support that far back?

**Comment by nickjj** [comment]
Thanks guys. Looks good.

Sounds like the `travis.yml` file should also get updated to include more modern versions of Node.

**Pull request merged**
