### PR TITLE
Updated package.json to allow webpack v2.2.0.

### PR DESCRIPTION
**Pull request by rohitkrai03**
What kind of change does this PR introduce?

Dependency update

Did you add or update the examples/?
No

Summary

Allow webpack 2.2.0 without peer dep warning

Does this PR introduce a breaking change?

No

Other information

### CODE REVIEW

**Comment by lgordey** [comment]
+1

**Comment by nickjj** [comment]
Thanks.

**Comment by lgordey** [comment]
@nickjj Hi! Can u bump new version with this changes pls?

**Comment by DrUNE** [comment]
@lgordey +1
@nickjj Hi! Can u bump new version with this changes pls?

**Comment by nickjj** [comment]
@lgordey @DrUNE It's updated to v0.4.0.

https://www.npmjs.com/package/manifest-revision-webpack-plugin

**Pull request merged**
