### PR TITLE
Now ignorePath takes into account full path with file name

### LINKED ISSUE #14: No possibility to ignore exact files
I would like to have a possibility to ignore not only file catalog path but full path to the file.
For example, I could have `.DS_Store` in some folder and I would like to ignore it.

It could be easily done with an update of `walkAndPrefetchAssets` function. I could make PR if you think that it's a good idea.

### PR DESCRIPTION
**Pull request by boccob**
Fixes #14

### CODE REVIEW

**Comment by nickjj** [comment]
Thanks, would you mind making the following change in the readme commit?

Change:
`ignorePaths` is an array of paths to ignore. Path could be string or regexp.

To:
`ignorePaths` is an array of paths to ignore. Path could be a string or regexp.

**Comment by boccob** [comment]
Done.

**Comment by nickjj** [comment]
Thanks for the contribution.

**Comment by nickjj** [comment]
I haven't tested this personally yet, but it still supports directories right?

**Comment by boccob** [comment]
Yes, it does.

**Comment by nickjj** [comment]
Great, thanks.

It's now a part of the newly released `v0.1.0` version, which is available on npm.

**Pull request merged**
